### ISSUE TITLE
Question: How do you avoid an endless loop from circular referencing files?

### ISSUE THREAD

**Issue by miltoncandelero** [rocket-ua/pixi-tps-loader#1]
if all the json files have the `related_multi_packs` field and two files reference each other... how do you avoid a loop where the first file adds the second and the second adds the first?

I haven't used your code yet, I was looking into it and realized this is a bit confusing for me

**Comment by rocket-ua** [comment]
> if all the json files have the `related_multi_packs` field and two files reference each other... how do you avoid a loop where the first file adds the second and the second adds the first?
> 
> I haven't used your code yet, I was looking into it and realized this is a bit confusing for me

@miltoncandelero Hi. I just checking if this file already in resources, and if yes, skip adding this file for downloading.
[`if (this.resources[itemName] || this.resources[itemUrl]) {  @return; } `](https://github.com/rocket-ua/pixi-tps-loader/blob/ff304f6b616283e25693c0add1f99978e6d06231/src/ResourceLoader.js#L23)
You can try this library and look how its works.

**Comment by miltoncandelero** [comment]
Oh, I feel dumb I missed that. Thank You.

PS: have you considered using the smaller imports instead of importing * from PIXI?
(A.K.A `Import {Loader} from PIXI`) however I don't know if those kind of imports work on pixi 4 or lower :/

**Comment by rocket-ua** [comment]
> Oh, I feel dumb I missed that. Thank You.
> 
> PS: have you considered using the smaller imports instead of importing * from PIXI?
> (A.K.A `Import {Loader} from PIXI`) however I don't know if those kind of imports work on pixi 4 or lower :/

Hm... I thing I need to check about smaller imports. Thank you for idea :)
