### ISSUE TITLE
ILoaderOptions error on loadType?

### ISSUE THREAD

**Issue by miltoncandelero** [rocket-ua/pixi-tps-loader#2]
I was trying to understand your lib (again) and found that you do this:

`xhrType: PIXI.LoaderResource.TYPE.JSON`

https://github.com/rocket-ua/pixi-tps-loader/blob/master/src/ResourceLoader.js#L29

However, when I dropped it into typescript it went bananas on me because `xhrType` is a string and `TYPE.JSON` is a number!

I checked and the two fields are similar and really confusing.

```
loadType: PIXI.LoaderResource.TYPE.JSON,
xhrType: PIXI.LoaderResource.XHR_RESPONSE_TYPE.JSON,
```

---

Not sure if this could bring any problem in the future and maybe Pixi does some js magic behind it and it fixes itself. I am not sure but I thought it could be useful to bring up

**Comment by rocket-ua** [comment]
@miltoncandelero hi :) I think you right, and it's my mistake. Thank you for comment.
